[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200

lib_deps = 
    m5stack/M5Unified
    m5stack/M5GFX
    m5stack/M5CoreS3
    espressif/esp32-camera@^2.0.4
    esphome/AsyncTCP-esphome@^2.1.4
    https://github.com/me-no-dev/ESPAsyncWebServer.git

build_flags = 
    -DASYNC_TCP_RUNNING_CORE=1
    -DASYNC_TCP_STACK_SIZE=4096
